<a href="https://colab.research.google.com/github/MeenakshiRajpurohit/CMPE-255-Data-Mining/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
import numpy as np
import pandas as pd

* `torch.tensor()`: This function takes input such as a Python list to convert it into a tensor.

In [7]:
x = torch.tensor([1,2,3])

print("from python list:",x)
print("tensor datatype:", x.dtype)

from python list: tensor([1, 2, 3])
tensor datatype: torch.int64



* `torch.from_numpy()`: Converts a NumPy array into a PyTorch tensor.

In [8]:
numpy_array = np.array([[1,2,3], [4,5,6]])
torch_tensor_from_numpy = torch.from_numpy(numpy_array)

print('tensor from numpy', torch_tensor_from_numpy)

tensor from numpy tensor([[1, 2, 3],
        [4, 5, 6]])



* **From a pandas DataFrame**: Pandas is a Python library for working with data organized in rows and columns, like a CSV file or spreadsheet. A DataFrame is pandas' main data structure for storing this kind of tabular data. DataFrames are one of the most common ways to load and explore datasets in machine learning, especially when reading CSV files. There isn't a direct function to convert a DataFrame to a tensor. The standard method is to extract the data from the DataFrame into a NumPy array using the `.values` attribute, and then convert that array into a tensor using `torch.tensor()`.

In [9]:
df = pd.read_csv('/content/data.csv')

all_values = df.values

tensor_from_df = torch.tensor(all_values)

print('original dataframe:', df)

original dataframe:    distance_miles  delivery_time_minutes
0            1.60                   7.22
1           13.09                  32.41
2            6.97                  17.47


In [10]:
print('resulting tensor', tensor_from_df)

resulting tensor tensor([[ 1.6000,  7.2200],
        [13.0900, 32.4100],
        [ 6.9700, 17.4700]], dtype=torch.float64)


In [11]:
print('tensor from data type', tensor_from_df.dtype)

tensor from data type torch.float64


### 1.2 - With Predefined Values

Sometimes you need to create tensors for specific purposes, like initializing a model's weights and biases before training begins. PyTorch allows you to quickly generate tensors filled with placeholder values like zeros, ones, or random numbers, which is useful for testing and setup.

* `torch.zeros()`: Creates a tensor filled with zeros of the specified dimensions.

In [12]:
#all zeros

zeros = torch.zeros(2,3)

print('tensor with zero', zeros)

tensor with zero tensor([[0., 0., 0.],
        [0., 0., 0.]])



* `torch.ones()`: Creates a tensor filled with ones of the specified dimensions.

In [13]:
ones = torch.ones(2,3)

print('tensor with ones:', ones)

tensor with ones: tensor([[1., 1., 1.],
        [1., 1., 1.]])


* `torch.rand()`: Generates a tensor with random numbers uniformly distributed between 0 and 1, based on the specified dimensions.

In [14]:
random = torch.rand(2,3)

print('random tensor', random)

random tensor tensor([[0.8546, 0.6227, 0.6657],
        [0.8186, 0.1891, 0.6492]])


### 1.3 - From a Sequence

For situations where you need to generate a sequence of data points, such as a range of values for testing a model's predictions, you can create a tensor directly from that sequence.

* `torch.arange()`: Creates a 1D tensor containing a range of numbers from the specified start value to one less than the specified stop value, incrementing (if positive) or decrementing (if negative) by the specified `step` value.

In [15]:
#range of numbers

range_tensor = torch.arange(0, 10, step=1)

print('arange tensor:', range_tensor)

arange tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## 2 - Reshaping & Manipulating

A very common source of errors in PyTorch projects is a mismatch between the shape of your input data and the shape your model expects. For instance, a model is typically designed to process a batch of data, so even if you want to make a single prediction, you must shape your input tensor to look like a batch of one. Mastering tensor reshaping is a key step toward building and debugging models effectively.

### 2.1 - Checking a Tensor's Dimensions

The first step to fixing a shape mismatch is to understand the current dimensions of your tensor. Checking the shape is your primary debugging tool. It tells you how many samples you have and how many features are in each sample.

* `torch.Tensor.shape`: An attribute that returns a `torch.Size` object detailing the size of the tensor along each dimension.

In [16]:
#a 2d tensor

x = torch.tensor([[1,2,3],
                  [4,5,6]])

print('original tensor', x)
print('tensor shape', x.shape)

original tensor tensor([[1, 2, 3],
        [4, 5, 6]])
tensor shape torch.Size([2, 3])


### 2.2 - Changing a Tensor's Dimensions

Once you identify a shape mismatch, you need to correct it. A frequent task is adding a dimension to a single data sample to create a batch of size one for your model, or removing a dimension after a batch operation is complete.

* **Adding Dimension:** `torch.Tensor.unsqueeze()` inserts a new dimension at the specified index.
    * *Notice how the shape will change from `[2, 3]` to `[1, 2, 3]` and the tensor gets wrapped in an extra pair of square brackets `[]`*.

In [17]:
print('original tensor',x)
print('original shape', x.shape)

#add dimension
expanded = x.unsqueeze(0) #add dimension at index zero

print('tensor with added dimension at index 0', expanded)
print('tensor shape', expanded.shape)

original tensor tensor([[1, 2, 3],
        [4, 5, 6]])
original shape torch.Size([2, 3])
tensor with added dimension at index 0 tensor([[[1, 2, 3],
         [4, 5, 6]]])
tensor shape torch.Size([1, 2, 3])



* **Removing Dimension:** `torch.Tensor.squeeze()` removes dimensions of size 1.
    * *This reverses the unsqueeze operation, removing the `1` from the shape and taking away a pair of outer square brackets*.

In [18]:
print('expanded tensor', expanded)
print('tesnor shape', expanded.shape)

#remove dimension


squeezed = expanded.squeeze()

print('tensor with dimensions removed', squeezed)
print('tensoe shape', squeezed.shape)

expanded tensor tensor([[[1, 2, 3],
         [4, 5, 6]]])
tesnor shape torch.Size([1, 2, 3])
tensor with dimensions removed tensor([[1, 2, 3],
        [4, 5, 6]])
tensoe shape torch.Size([2, 3])


### 2.3 - Restructuring

Beyond just adding or removing dimensions, you may need to completely change a tensor's structure to match the requirements of a specific layer or operation within your neural network.

* **Reshaping:** `torch.Tensor.reshape()` changes the shape of a tensor to the specified dimensions.

In [19]:
reshaped = x.reshape(3,2)

print(reshaped)
print(reshaped.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])


* **Transposing:** `torch.Tensor.transpose()` swaps the specified dimensions of a tensor.

In [20]:
transposed = x.transpose(0,1)

print(transposed)
print(transposed.shape)

tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2])


### 2.4 - Combining Tensors

In the data preparation stage, you might need to combine data from different sources or merge separate batches into one larger dataset.

* `torch.cat()`: Joins a sequence of tensors along an existing dimension. Note: All tensors must have the same shape in dimensions other than the one being concatenated.

In [21]:
tensor_a = torch.tensor([[1,2],
                         [3,4]])
tensor_b = torch.tensor([[5,6],
                         [7,8]])

concatenated_tensor = torch.cat((tensor_a, tensor_b), dim=1)

print(tensor_a)

print(tensor_b)
print(concatenated_tensor)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


## 3 - Indexing & Slicing

After you have your data in a tensor, you will often need to access specific parts of it. Whether you are grabbing a single prediction to inspect its value, separating your input features from your labels, or selecting a subset of data for analysis, indexing and slicing are the tools for the job.

### 3.1 - Accessing Elements

These are the fundamental techniques for getting data out of a tensor, working very similarly to how you would access elements in a standard Python list.

* **Standard Indexing**: Accessing single elements or entire rows using integer indices (e.g., `x[0]`, `x[1, 2]`).

In [25]:
#create a 3x4 tensor

x = torch.tensor([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
print(x)

single_element_tensor = x[1, 2]
print(single_element_tensor)

second_row = x[1]
print(second_row)

last_row = x[-1]
print(last_row)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor(7)
tensor([5, 6, 7, 8])
tensor([ 9, 10, 11, 12])



* **Slicing**: Extracting sub-tensors using `[start:end:step]` notation (e.g., `x[:2, ::2]`).
    * *Note: The `end` index itself is not included in the slice.*
* Slicing can be used to access entire columns.

In [30]:
print(x)

first_two_rows = x[0:2]
print(first_two_rows)

third_column = x[:,2]
print(third_column)

every_other_column = x[:, ::2]

last_column = x[:, -1]

print(every_other_column)
print(last_column)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([ 3,  7, 11])
tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])
tensor([ 4,  8, 12])


* **`.item()`**: Extracts the value from a single-element tensor as a standard Python number.

In [33]:
print(single_element_tensor)

value = single_element_tensor.item()

print(value)

print(type(value))

tensor(7)
7
<class 'int'>


### 3.2 - Advanced Indexing

For more complex data selection, such as filtering your dataset based on one or more conditions, you can use advanced indexing techniques.

* **Boolean Masking**: Using a boolean tensor to select elements that meet a certain condition (e.g., `x[x > 5]`).

In [36]:
print(x)

mask = x > 6

print(mask)

mask_applied = x[mask]

print(mask_applied)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[False, False, False, False],
        [False, False,  True,  True],
        [ True,  True,  True,  True]])
tensor([ 7,  8,  9, 10, 11, 12])


* **Fancy Indexing**: Using a tensor of indices to select specific elements in a non-contiguous way.

In [38]:
print(x)

row_indices = torch.tensor([0, 2])

column_indices = torch.tensor([1, 3])

get_values = x[row_indices[:, None], column_indices]

print(get_values)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 2,  4],
        [10, 12]])


## 4 - Mathematical & Logical Operations

At their core, neural networks are performing mathematical computations. A single neuron, for example, calculates a weighted sum of its inputs and adds a bias. PyTorch is optimized to perform these operations efficiently across entire tensors at once, which is what makes training so fast.

### 4.1 - Arithmetic

These operations are the foundation of how a neural network processes data. You'll see how PyTorch handles element-wise calculations and uses a powerful feature called broadcasting to simplify your code.

* **Element-wise Operations**: Standard math operators (`+`, `*`) that apply to each element independently.

In [40]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

element_add = a + b

print(element_add)

element_multiply = a * b #element wise multiplication

print(element_multiply)

tensor([5, 7, 9])
tensor([ 4, 10, 18])


* **Dot Product (`torch.matmul()`)**: Calculates the dot product of two vectors or matrices.

In [41]:
dot_product = torch.matmul(a, b)

print(dot_product)

tensor(32)


* **Broadcasting**: The automatic expansion of smaller tensors to match the shape of larger tensors during arithmetic operations.
    * Broadcasting allows operations between tensors with compatible shapes, even if they don't have the exact same dimensions.

In [44]:
a = torch.tensor([1,2,3])

b = torch.tensor(
    [[1],
     [2],
     [3]]
)

#apply broadcasting

c = a + b

print(c)

print(c.shape)

tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])
torch.Size([3, 3])


### 4.2 - Logic & Comparisons

Logical operations are powerful tools for data preparation and analysis. They allow you to create boolean masks to filter, select, or modify your data based on specific conditions you define.

* **Comparison Operators**: Element-wise comparisons (`>`, `==`, `<`) that produce a boolean tensor.

In [48]:
temperatures = torch.tensor([20, 35, 19, 35, 42])

print(temperatures)

is_hot = temperatures > 30

is_cool = temperatures <=20

is_35_degress = temperatures == 35

print(is_hot)

print(is_cool)

print(is_35_degress)

tensor([20, 35, 19, 35, 42])
tensor([False,  True, False,  True,  True])
tensor([ True, False,  True, False, False])
tensor([False,  True, False,  True, False])



* **Logical Operators**: Element-wise logical operations (`&` for **AND**, `|` for **OR**) on boolean tensors.

In [53]:
is_morning = torch.tensor([True, False, True, False, True])

is_raining = torch.tensor([False, True, False, True, False])

morning_and_raining = (is_morning & is_raining)

print(morning_and_raining)

morning_or_raining = (is_morning | is_raining )
print(morning_or_raining)

tensor([False, False, False, False, False])
tensor([True, True, True, True, True])


### 4.3 - Statistics

Calculating statistics like the mean or standard deviation can be useful for understanding your dataset or for implementing certain types of normalization during the data preparation phase.

* `torch.mean()`: Calculates the mean of all elements in a tensor.

In [58]:
data = torch.tensor([10., 20., 30., 40.])

data_mean = data.mean()

print(data_mean)

data_std = data.std()

print(data_std)

tensor(25.)
tensor(12.9099)


### 4.4 - Data Types

Just as important as a tensor's shape is its data type. Neural networks typically perform their calculations using 32-bit floating point numbers (float32). Providing data of the wrong type, such as an integer, can lead to runtime errors or unexpected behavior during training. It is a good practice to ensure your tensors have the correct data type for your model.

* **Type Casting (`.int`, etc.)**: Converts a tensor from one data type to another (e.g., from float to integer).

In [59]:
print(data)

tensor([10., 20., 30., 40.])


In [62]:
print(data.dtype)

Int_tensor = data.int()
print(Int_tensor)

torch.float32
tensor([10, 20, 30, 40], dtype=torch.int32)
